### ISSUE TITLE
Logic problem in sorting

### ISSUE THREAD

**Issue by LEQADA** [sphereio/sphere-stock-export#11] opened 2016-12-09 12:27 UTC
There is a logic problem in creating requests. For example our request looks like this:

    https://api.sphere.io/carhartt-production/inventory?where=supplyChannel(not id="xxxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxx" and not id="yyyyyyy-yyyy-yyyy-yyyy-yyyyyyyy") and id > "zzzzzz-zzzzz-zzzz-zzzz-zzzzzzzzzz"&sort=sku asc&expand=supplyChannel&limit=50&withTotal=false

[We sort by `sku`](https://github.com/sphereio/sphere-stock-export/blob/master/src/coffee/fetchstocks.coffee#L11) but [pagening in sphere-node-sdk works by `id`](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/connect/rest.coffee#L205). We don't need to override sorting in this module. In other case we will not get all products.

**Comment by hisabimbola** [comment] 2016-12-09 16:28
I really do not get what the pain point is here.

Looking at this [code](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/services/base.coffee#L319), it never uses SDK default paging logic if query string is set. and from [here](https://github.com/sphereio/sphere-stock-export/blob/master/src/coffee/fetchstocks.coffee#L21) and [here](https://github.com/sphereio/sphere-stock-export/blob/master/src/coffee/fetchstocks.coffee#L19), queryString is always set.

Can you please explain what the issue is and what #12 is solving.

**Comment by LEQADA** [comment] 2016-12-09 17:22
If it's not empty then it will call `_paged` which will call `PAGED` from rest.js
Try to put some debug outputs.

**Comment by butenkor** [comment] 2016-12-11 17:09
@hisabimbola I might be wrong but i think params.queryString in base is only set if [byQueryString function](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/services/base.coffee#L269) is used. Setting additional query parameters over dedicated functions like ".where" is allowed with pagination done by SDK (if "all" is used). The issue is actually [here](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/services/base.coffee#L321) and [here](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/connect/rest.coffee#L205) as rest uses sort by "sku" for a query but does pagination by "id" which results that lots of data is missed and not fetched. Maybe it should be fixed not here but rather in SDK instead so it should use query sort attribute for pagination also and not id only.

**Comment by hisabimbola** [comment] 2016-12-12 06:32
Ach so, I see the edge case now.

So if queryString is not set, it uses the paged function in the SDK. I think this solution is the quick and easy one, but as @butenkor rightly pointed out, the SDK needs to be updated also, so that a custom sort parameter can be passed in.

**Closed as completed** 2017-02-06 09:28 UTC
